# Generated by Django 3.2.7 on 2021-09-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Project',
        ),
    ]
